config/routes.rb
Rails.application.routes.draw do
  resources :tomorrows
  root 'tomorrows#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tomorrow.rb
class Tomorrow < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tomorrows_controller.rb
class TomorrowsController < ApplicationController
  before_action :set_tomorrow, only: [:show, :edit, :update, :destroy]

  # GET /tomorrows
  # GET /tomorrows.json
  def index
    @tomorrow = Tomorrow.new
    @tomorrows = Tomorrow.all
  end

  # GET /tomorrows/1
  # GET /tomorrows/1.json
  def show
  end

  # GET /tomorrows/new
  def new
    @tomorrow = Tomorrow.new
  end

  # GET /tomorrows/1/edit
  def edit
  end

  # POST /tomorrows
  # POST /tomorrows.json
  def create
    @tomorrow = Tomorrow.new(tomorrow_params)

    respond_to do |format|
      if @tomorrow.save
        format.html { redirect_to root_path}
        format.json { render :show, status: :created, location: @tomorrow }
      else
        format.html { render :new }
        format.json { render json: @tomorrow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tomorrows/1
  # PATCH/PUT /tomorrows/1.json
  def update
    respond_to do |format|
      if @tomorrow.update(tomorrow_params)
        format.html { redirect_to @tomorrow, notice: 'Tomorrow was successfully updated.' }
        format.json { render :show, status: :ok, location: @tomorrow }
      else
        format.html { render :edit }
        format.json { render json: @tomorrow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tomorrows/1
  # DELETE /tomorrows/1.json
  def destroy
    @tomorrow.destroy
    respond_to do |format|
      format.html { redirect_to tomorrows_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tomorrow
      @tomorrow = Tomorrow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tomorrow_params
      params.require(:tomorrow).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tomorrows_helper.rb
module TomorrowsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Plan
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
  	#body
    	= yield

app/views/tomorrows/_form.html.slim
.form  
  = form_for(tomorrow, remote: true) do |f|
    - if tomorrow.errors.any?
      #error_explanation
        h2
          = pluralize(tomorrow.errors.count, "error")
          | prohibited this tomorrow from being saved:
        ul
          - tomorrow.errors.full_messages.each do |message|
            li= message
    span.field
      = f.text_field :name
    span.actions
      = f.submit

app/views/tomorrows/edit.html.erb
<h1>Editing Tomorrow</h1>

<%= render 'form', tomorrow: @tomorrow %>

<%= link_to 'Show', @tomorrow %> |
<%= link_to 'Back', tomorrows_path %>

app/views/tomorrows/index.html.slim
p#notice= notice
h1 Plans
= render 'form', tomorrow: @tomorrow
table
  thead
    tr
      th colspan="3" 
  tbody
    - @tomorrows.each do |tomorrow|
      tr
        td.name= tomorrow.name
        td= link_to 'Show', tomorrow
        td= link_to 'Edit', edit_tomorrow_path(tomorrow)
        td= link_to 'Destroy', tomorrow, method: :delete, remote: true
br/

/ = link_to 'New Tomorrow', new_tomorrow_path

app/views/tomorrows/new.html.erb
<h1>New Tomorrow</h1>

<%= render 'form', tomorrow: @tomorrow %>

<%= link_to 'Back', tomorrows_path %>

app/views/tomorrows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tomorrow.name %>
</p>

<%= link_to 'Edit', edit_tomorrow_path(@tomorrow) %> |
<%= link_to 'Back', tomorrows_path %>